Models/Animal.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace BW5.Models
{
    public class Animal
    {
        [Key]
        public int id { get; set; }
        [Column(TypeName = "datetime2")]
        [Required]
        public DateTime DataReg { get; set; } = DateTime.Now;
        public string Name { get; set; }
        [Required]
        public string Tipologia { get; set; }
        public string Colore { get; set; }
        [Column(TypeName = "datetime2")]
        public DateTime DataNascita { get; set; }
        [StringLength(32)]
        [Index(IsUnique = true)]
        public string IdMicrochip { get; set; }
        [Required]
        public string NomeProprietario { get; set; } = "Comune di Napoli";
        public string CognomeProprietario { get; set; }
        [Required]
        public string TelefonoProprietario { get; set; } = "0817951111";
        [Required]
        public string Foto { get; set; }
        [Required]
        [Display(Name = "Presunta?")]
        public bool Presunta { get; set; } = false;

        [NotMapped]
        public Admission admission { get; set; } = new Admission();
        public virtual ICollection<Admission> Admission { get; set; }
        public virtual ICollection<Therapy> Therapy { get; set; }

    }
}

Models/AnimalsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BW5.Models
{
    public class AnimalsViewModel
    {
        public Admission admission { get; set; }
        public Therapy therapy { get; set; }
    }
}

Models/Therapy.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace BW5.Models
{
    public class Therapy
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [Column(TypeName = "datetime2")]
        public DateTime DataCura { get; set; }
        [Required]
        public string Diagnosi { get; set; }
        [Required]
        public string DescrizioneCura { get; set; }
        public Animal Animal { get; set; }
    }
}

Controllers/AnimalController.cs
using System.Data.Entity;
using System.Threading.Tasks;
using System.Web.Mvc;
using BW5.Models;

public class AnimalController : Controller
{
    private readonly VetContext _db;

    public AnimalController()
    {
        _db = new VetContext();
    }

    public ActionResult SearchAnimal()
    {
        return View();
    }

    [HttpPost]
    public async Task<ActionResult> SearchAnimal(string microchipNumber)
    {
        var animal = await _db.Animals.FirstOrDefaultAsync(a => a.IdMicrochip == microchipNumber);

        if (animal == null)
        {
            TempData["ErrorMessage"] = "Nessun animale trovato con questo microchip.";
            return RedirectToAction("Index");
        }

        return PartialView("_AnimalDetailsPartial", animal);
    }
}

Controllers/VetController.cs
using BW5.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BW5.Controllers
{
    public class VetController : Controller
    {
        // GET: Vet
        private VetContext db = new VetContext();

        public ActionResult Animals()
        {
            return View(db.Animals.ToList());
        }

    }
}

Views/Vet/Animals.cshtml
@using BW5.Models;
@model AnimalsViewModel
@{
    ViewBag.Title = "Animals";
    var animals = ViewBag.Animals as List<Animal>;
}


<h2>Animals</h2>

@if (TempData["error"] != null)
{
    <p>@TempData["error"]</p>
}
@Html.ActionLink("Monthly", "Mensili", "Vet")
<table class="table">
    <thead>

        <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">Tipologia</th>
            <th scope="col">Colore</th>
            <th scope="col">Foto</th>
            <th scope="col">Data Registrazione</th>
            <th scope="col">Data di Nascita</th>
            <th scope="col">Presunta?</th>
            <th scope="col">Nome Proprietario</th>
            <th scope="col">Cognome Proprietario</th>
            <th scope="col">Telefono Proprietario</th>
            <th scope="col">Microchip</th>
            <th scope="col">Controlli</th>

        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < animals.Count(); i++)
        {
            <tr>

                <th scope="row">@animals[i].id</th>
                <td>@animals[i].Name</td>
                <td>@animals[i].Tipologia</td>
                <td>@animals[i].Colore</td>
                <td><img style="width: 100px; height: 100px; object-fit: cover;" src="@animals[i].Foto" alt="@animals[i].Name" /></td>
                <td>@animals[i].DataReg.ToShortDateString()</td>
                <td>@animals[i].DataNascita.ToShortDateString()</td>
                <td>@animals[i].Presunta</td>
                <td>@animals[i].NomeProprietario</td>
                <td>@animals[i].CognomeProprietario</td>
                <td>@animals[i].TelefonoProprietario</td>
                <td>@animals[i].IdMicrochip</td>
                <td>
                    @using (Html.BeginForm("Ricovero", "Vet", new { animalId = animals[i].id }, FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#Modal(@animals[i].id)">
                            Ricovero
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="Modal(@animals[i].id)" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5">Modal title</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        @Html.HiddenFor(m => m.admission.animalID)

                                        @Html.LabelFor(m => m.admission.DataInizio, new { htmlAttributes = new { @class = "form-label" } })
                                        @Html.EditorFor(m => m.admission.DataInizio, new { htmlAttributes = new { @class = "form-control", @max = $"{@DateTime.Now.ToString("yyyy-MM-dd")}" } })

                                        @Html.LabelFor(m => m.admission.DataFine, new { htmlAttributes = new { @class = "form-label" } })
                                        @Html.EditorFor(m => m.admission.DataFine, new { htmlAttributes = new { @class = "form-control", @max = $"{@DateTime.Now.ToString("yyyy-MM-dd")}" } })


                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        <button type="submit" class="btn btn-primary">Conferma ricovero</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }

                </td>
            </tr>
        }

    </tbody>
</table>

@section scripts {
    <script type="text/javascript">
    </script>
}

Views/Vet/Mensili.cshtml
@using BW5.Models;
@model List<Admission>
@{
    ViewBag.Title = "Mensili";
    List<Admission> list = new List<Admission>();
}

<h2>Mensili</h2>

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Data Inizio Ricovero</th>
            <th scope="col">Nome</th>
            <th scope="col">Tipologia</th>
            <th scope="col">Colore</th>
            <th scope="col">Data Registrazione Animale</th>
            <th scope="col">Data di Nascita</th>
            <th scope="col">#Microchip</th>

        </tr>
    </thead>
    <tbody id="target">
    </tbody>
</table>

@section scripts {
    <script type="text/javascript">
        const table = document.getElementById("target")

        async function FetchMonthly() {
            const response = await fetch('@Url.Action("Monthly", "Vet")')
            const data = await response.json();
            for (elem of data) {
                const tr = document.createElement("tr")
                table.appendChild(tr)
                for (let [key, value] of Object.entries(elem)) {
                    if (key == "DataReg" || key == "DataNascita" || key == "StartDate") {
                        value = new Date(parseInt(value.substr(6))).toISOString().slice(0,10)
                    }
                    const td = document.createElement("td")
                    td.innerText = value
                    tr.appendChild(td)
                }
            }


            return data
        }
        FetchMonthly();

    </script> }

Views/Vet/Therapy.cshtml
@model BW5.Models.AnimalTherapyViewModel

<h2>Visita per l'animale: @Model.Animal.Name</h2>
<p>Data Registrazione: @Model.Animal.DataReg.ToShortDateString()</p>
<p>Tipo di Animale: @Model.Animal.Tipologia</p>
<p>Proprietario: @Model.Animal.NomeProprietario</p>
<p>Telefono Proprietario: @Model.Animal.TelefonoProprietario</p>

@if (Model.Therapies.Any())
{
    <h3>Cronistoria delle Visite:</h3>

    <table class="table">
        <tr>
            <th>Data della Visita</th>
            <th>Diagnosi</th>
            <th>Descrizione Cura</th>
        </tr>
        @foreach (var terapia in Model.Therapies)
        {
            <tr>
                <td>@terapia.DataCura.ToShortDateString()</td>
                <td>@terapia.Diagnosi</td>
                <td>@terapia.DescrizioneCura</td>
            </tr>
        }
    </table>
}
else
{
    <p>Non ci sono terapie registrate per questo animale.</p>
}

<h3>Inserisci Nuova Terapia:</h3>

<form action="@Url.Action("NewTherapy", "Vet")" method="post">
    <input type="hidden" id="AnimalId" name="AnimalId" value="@Model.Animal.id" />
    <div class="form-group">
        <label for="DataCura" class="control-label">Data Cura</label>
        <input type="date" id="DataCura" name="DataCura" class="form-control" />
        <span class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="Diagnosi" class="control-label">Diagnosi</label>
        <input type="text" id="Diagnosi" name="Diagnosi" class="form-control" />
        <span class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="DescrizioneCura" class="control-label">Descrizione Cura</label>
        <input type="text" id="DescrizioneCura" name="DescrizioneCura" class="form-control" />
        <span class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Salva</button>
</form>
<p>@Html.ActionLink("Torna indietro", "Animals", "Vet")</p>