Models/Animal.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace BW5.Models
{
    public class Animal
    {
        [Key]
        public int id { get; set; }
        [Column(TypeName = "datetime2")]
        [Required]
        public DateTime DataReg { get; set; } = DateTime.Now;
        public string Name { get; set; }
        [Required]
        public string Tipologia { get; set; }
        public string Colore { get; set; }
        [Column(TypeName = "datetime2")]
        public DateTime DataNascita { get; set; }
        [StringLength(32)]
        [Index(IsUnique = true)]
        public string IdMicrochip { get; set; }
        [Required]
        public string NomeProprietario { get; set; } = "Comune di Napoli";
        public string CognomeProprietario { get; set; }
        [Required]
        public string TelefonoProprietario { get; set; } = "0817951111";
        [Required]
        public string Foto { get; set; }
        [Required]
        [Display(Name = "Presunta?")]
        public bool Presunta { get; set; } = false;

        [NotMapped]
        public Admission admission { get; set; } = new Admission();
        public virtual ICollection<Admission> Admission { get; set; }
        public virtual ICollection<Therapy> Therapy { get; set; }

    }
}

Models/AnimalsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BW5.Models
{
    public class AnimalsViewModel
    {
        public Admission admission { get; set; }
        public Therapy therapy { get; set; }
    }
}

Controllers/AnimalController.cs
using System.Data.Entity;
using System.Threading.Tasks;
using System.Web.Mvc;
using BW5.Models;

public class AnimalController : Controller
{
    private readonly VetContext _db;

    public AnimalController()
    {
        _db = new VetContext();
    }

    public ActionResult SearchAnimal()
    {
        return View();
    }

    [HttpPost]
    public async Task<ActionResult> SearchAnimal(string microchipNumber)
    {
        var animal = await _db.Animals.FirstOrDefaultAsync(a => a.IdMicrochip == microchipNumber);

        if (animal == null)
        {
            TempData["ErrorMessage"] = "Nessun animale trovato con questo microchip.";
            return RedirectToAction("Index");
        }

        return PartialView("_AnimalDetailsPartial", animal);
    }
}

Views/Animal/SearchAnimal.cshtml
@model string

@{
    ViewData["Title"] = "Ricerca Animali";
}

<h2>Ricerca Animali</h2>

<form id="searchForm">
    <input type="text" id="microchipNumber" name="microchipNumber" value="@Model" />
    <button type="submit">Cerca</button>
</form>

<div id="animalDetails"></div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#searchForm').submit(function (e) {
                e.preventDefault();
                var microchipNumber = $('#microchipNumber').val();
                $.ajax({
                    url: '@Url.Action("SearchAnimal", "Animal")',
                    type: 'POST',
                    data: { microchipNumber: microchipNumber },
                    success: function (data) {
                        $('#animalDetails').html(data);
                    }
                });
            });
        });
    </script>
}

Views/Animal/_AnimalDetailsPartial.cshtml
@model BW5.Models.Animal

<h4>Dettagli dell'animale:</h4>
<ul>
    <li>Nome: @Model.Name</li>
    <li>Tipologia: @Model.Tipologia</li>
    <li>Colore: @Model.Colore</li>
    <li>Data di nascita: @Model.DataNascita.ToShortDateString()</li>
    <li>Nome del proprietario: @Model.NomeProprietario</li>
</ul>